[package]
name = "chip"
version = "0.1.0"
authors = ["louis <louis@jnnll.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.11.2"
rand = "0.4.0"